language: generic
# Letting travis know we need super user level permissions to run this build (since we need this for Docker)
sudo: required
# Let Travis know we need the Docker cli installed
services:
  - docker
# Series of commands that we need to run before we do our travis action (i,e. Run our tests / deploy our app)
before_install:
  - docker build -t juankimorales/docker-practice-react -f Dockerfile.dev .

# Section for the commands that we need to run our test suite
# Travis will watch the output of these commands. If it ever gets a status code != 0, it will assume something went wrong
# NOTE: Travis assumes that these commands exit automatically. In the case of npm run test, by default that is not the case
script:
  - docker run -e CI=true juankimorales/docker-practice-react npm run test

# Section that handles deploying
deploy:
  # Travis is pre-configured for deploying to various services like EBS
  provider: elasticbeanstalk
  # AWS region where our EBS is
  region: "us-east-2"
  # Application name
  app: "docker-practice-react"
  # Environment name
  env: "DockerPracticeReact-env"
  # Name of the bucket that travis will put the zip file of our application into. Can be found in S3
  bucket_name: "elasticbeanstalk-us-east-2-298694261941"
  # Path for the folder where we will save our zip file. Generally the app name
  bucket_path:  "docker-practice-react"
  # Only deploy the application when code is pushed to master
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY